### ISSUE TITLE
Gas value remains at 0

### ISSUE THREAD

**Issue by xb385** [daniel-jong/esp8266_p1meter#16]

**Comment by jschaeke** [comment]
@KurtKeunen  How did you solve it? Here's it still 0 (using Fluvius)
```
sensors/power/p1meter/gas_meter_m3 -> 0
```

**Comment by KurtKeunen** [comment]
> @KurtKeunen  How did you solve it? Here's it still 0 (using Fluvius)
> ```
> sensors/power/p1meter/gas_meter_m3 -> 0
> ```

Check my profile, i made my solution public repo
