### ISSUE TITLE
Error during compiling: 'TX' was not declared in this scope

### ISSUE THREAD

**Issue by gustavstrandberg** [daniel-jong/esp8266_p1meter#2]
Hi! 

First of all, thanks for a great job!

I got an Landis+Gyr E360 installed last week and I am trying to read out information from the P1 port.
I have an Wemos D1 mini ver 1, connected to a R11 cable according to your pictures.

I get an error compiling the code "'TX' was not declared in this scope".
If I change '#define SERIAL_TX TX' to '#define SERIAL_TX D0' in settings.h I can complie the code and upload. But i do not get any response from ther E360 meter. The only action I see is that I get a message over MQTT saying "p1 meter alive: p1meter". But thats it.

The serial monitor does not give anything out of the ordinary.
It confirms that it inverts UART0 RX, connects to WiFi and MQTT.

I am using Arduino IDE 1.8.13 and have downloaded the latest PubSubClient and WifiManager.

Help to resolve this is gladly appriciated. 

Thanks,
Gustav

**Comment by daniel-jong** [comment]
Hi Gustav,

Could you check if you have selected the correct board in the arduino? 
The RX and TX constants are set automagically based on the board you select. I'm also using a D1 mini v1 and using `LOLIN(WEMOS) D1 R2 & mini` as the selected board everything compiles without issue.

If this doesn't work be sure that you are using the correct pin numbers. _D0_ would be one of the 'normal' GPIO's, but in this fork we are using the _RX_ pin (and indirectly the _TX_ pin).
I think that you should try using _pin 1_ for the _TX_ and _pin 3_ for the _RX_.
![pinout](http://webshop.domoticx.nl/image/catalog/esp8266wifi/WEMOS/WEMOS%20D1%20mini%20Board%20v1/WEMOS%20D1%20mini%20Board%20v1%20pinout.jpg)

Let me know if this helps!

Regards, Daniel

**Comment by gustavstrandberg** [comment]
Hi Daniel and thanks for a fast answer!

I had selected "WeMos  D1 R1", selecting "LOLIN(WEMOS) D1 R2 & mini" worked.
Thanks!

Best regards
Gustav

**Comment by gustavstrandberg** [comment]
I have uploaded the compiled file, Still no response from the E360 meter. I will ask my electrical company if they need to activate the P1 port from their side.
/Gustav
