### ISSUE TITLE
Not connecting to wifi anymore

### ISSUE THREAD

**Issue by bartkodden** [daniel-jong/esp8266_p1meter#24]
Hi Daniel,

My nodemcu suddenly won't connect to the wifi I specified anymore. I tried 2 other SSIDs with no success. Does anyone have any experience with this issue?
I also tried removing the wifi credentials and completely reapplying them with no luck..

It has been working succesfully for the last 3 months...

Attached is my module info
![IMG_20221226_070917](https://user-images.githubusercontent.com/6901238/209510248-62fe1e7b-eed7-498c-8457-4657e713122a.jpg)

**Comment by daniel-jong** [comment]
Hard to say what’s the issue with something like this. Especially if you had it working before.

My first thought would be that I don’t think this is an software issue but something with your nodemcu. Try out a completely different library and see if your WiFi works on that. Like say; try out installing espHome or espEasy and see if that gets your WiFi running.

**Comment by bartkodden** [comment]
Will do!
Will report back with updates when I have some. I also thought about maybe updating the wifimanager version..
