### ISSUE TITLE
No hardware inverter needed?

### ISSUE THREAD

**Issue by grambas** [daniel-jong/esp8266_p1meter#25]
I found some other sources that reading from P1needs hardware inverter. For example:
http://domoticx.com/p1-poort-slimme-meter-uitlezen-hardware
https://www.zuidwijk.com/product/slimmelezer-plus/

I'm wondering how this wiring does not need it?

**Comment by daniel-jong** [comment]
The esp8266 is able to invert the p1 serial connection when connected to hardware serial   1 (with some limitations). This allows the signal to be inverted without any extra components.

Other libs have used the SoftwareSerial (think of that as an emulation layer) before but that is not fast enough for dsmr 5, and causes issues with incorrect messages.
