### ISSUE TITLE
Webserver

### ISSUE THREAD

**Issue by SchneHa** [daniel-jong/esp8266_p1meter#27]
Hi Daniel,

are you planning to implement a webserver to make sensor values visible? It would be great and also very useful if any change of credentials is needed. It would provide a very useful user interface using e.g. a smartphone.

**Comment by daniel-jong** [comment]
Hi,
Sorry, I have no intention of working on this. This product is intended as nothing more than a sensor. 
It's dependant on having a HomeAssistant setup to do the heavy lifting of creating nice graphs and show history (see https://www.home-assistant.io/dashboards/energy/). 

I consider power usage data to be useless without history, and the ESP just isn't the right platform (for me) to process this data.
You might consider using http://www.esp8266thingies.nl/wp/

Regards,
Daniël
