### ISSUE TITLE
esp stops sending data

### ISSUE THREAD

**Issue by PaulHeineman** [daniel-jong/esp8266_p1meter#32]
Hi, 
To start i'm pretty new with this so expect rookie mistakes. 
I had everything working just fine, however after 2 weeks my esp now stops sending data every couple of hours and sometimes it restarts automatically, but nog always. 
Below is the log, before, during and after it stopped working. 

![image](https://github.com/daniel-jong/esp8266_p1meter/assets/95190203/55440332-1f94-4cfb-9d8e-d914f9219c1e)

Thanks in advance for advice

**Comment by daniel-jong** [comment]
Hi,
My first guess would be that your dealing with some wifi connectivity issues.
The log you posted is from the MTTQ server, correct? 

You can connect to the ESP using a serial debugger and read the log files of the ESP itself. 
This might help you figure out what is going on.

**Comment by naeblizz** [comment]
I had a similar problem with my Esp8266. Everything working fine for about 3 weeks then suddenly it stopped sending data. Tried to restart it and connect it to my wifi again but it refused to connect to the network it was connected to before. Tried several reboots and connects. Had to create a whole new wifi network with new ssid then it worked again,
