### ISSUE TITLE
CRC invalid

### ISSUE THREAD

**Issue by RudyDevroey** [daniel-jong/esp8266_p1meter#35]
Hello,

I've used the sketch for more than a year without problems. Now, since the night from august 31 to september 1st at midnight I get the CRC invalid error. I tried with new hardware but still the same problem.

/FLU5\253769484_A

0-0:96.1.4(50217)

0-0:96.1.1(3153414733313035313637313630)

0-0:1.0.0(230903131547S)

1-0:1.8.1(005454.121*kWh)

1-0:1.8.2(006581.993*kWh)

1-0:2.8.1(000000.000*kWh)

1-0:2.8.2(000000.003*kWh)

0-0:96.14.0(0002)

1-0:1.4.0(00.217*kW)

1-0:1.6.0(230901161500S)(05.604*kW)

0-0:98.1.0(9)(1-0:1.6.0)(1-0:1.6.0)(230101000000W)(221217173000W)(06.422*kW)(230201000000W)(230103060000W)(04.788*kW)(230301000000W)(230215174500W)(04.517*kW)(230401000000S)(230313180000W)(03.939*kW)(230501000000S)(230421173000S)(04.295*kW)(230601000000S)(230528113000S)(04.692*kW)(230701000000S)(230625111500S)(06.655*kW)(230801000000S)(230709131500S)(05.514*kW)(230901000000S)(230820170000S)(04.510*kW)

k0.000*kW)

1-0:21.7.0(00.710*kW)

1-0:41.7.0(00.000*kW)

1-0:61.7.0(03.370*kW)

1-0:22.7.0(00.000*kW)

1-0:42.7.0(00.000*kW)

1-0:62.7.0(00.000*kW)

1-0:32.7.0(244.1*V)

1-0:52.7.0(000.0*V)

1-0:72.7.0(240.4*V)

1-0:31.7.0(003.40*A)

1-0:51.7.0(015.88*A)

1-0:71.7.0(014.03*A)

0-0:96.3.10(1)

0-0:17.0.0(999.9*kW)

1-0:31.4.0(999*A)

0-0:96.13.0()

!3E82

CRC Invalid!

**Comment by ExtinctSKB** [comment]
Same problem here, started at the same time.

**Comment by ExtinctSKB** [comment]
0-0:98.1.0 looks fishy especially the line after.

k0.000*kW)

In one of the telegrams I see the following for the line after

21.7.0(00.000*kw)

which is probably 1-0:21.7.0(00.000*kw) truncated. So either the telegram is wrong or something is wrong in the decoding.

I don't have an output from before 1st of september so I can't compare.

**Comment by fluppie** [comment]
Could this be related to the quarterly peak on Belgian DSMR meters?
https://esphome.io/components/sensor/dsmr.html
active_energy_import_current_average_demand
active_energy_import_maximum_demand_running_month
active_energy_import_maximum_demand_last_13_months

https://github.com/esphome/esphome/pull/5081

**Comment by ExtinctSKB** [comment]
That's what I was thinking. This capacity tariff started in January.  I'm suspecting that the size of 0-0:98.1.0 exceeded the buffer as soon as we reached September. But I haven't been able to test a bigger buffer yet.

**Comment by ExtinctSKB** [comment]
Could it be a bug in the meter itself where 0-0:98.1.0 is overwriting the next data object once it got too big (i.e. as of september 9 items)?

**Comment by RudyDevroey** [comment]
I just send an email to the tech helpdesk to ask what changed. I'll  keep you all informed.

**Comment by ccantill** [comment]
I disabled the CRC check and that fixes it somewhat, but certain fields are missing; I'm not receiving 1-0:1.7.0 nor 1-0:2.7.0 for example. Looks indeed like a bug in the meter.

**Comment by ccantill** [comment]
Turns out it's indeed an issue with the hardware serial buffer being overrun. Adding `Serial.setRxBufferSize(1024);` after `Serial.begin(...)` fixes it.

**Comment by RudyDevroey** [comment]
> It's an issue with the hardware serial buffer being overrun. Adding `Serial.setRxBufferSize(1024);` after `Serial.begin(...)` fixes it.

This did the trick. Thanks a lot.

**Comment by ExtinctSKB** [comment]
> It's an issue with the hardware serial buffer being overrun. Adding `Serial.setRxBufferSize(1024);` after `Serial.begin(...)` fixes it.

Confirmed, this solved it.

**Comment by Svenpscript** [comment]
Confirmed, this solved it. This item can be closed. Thanks!
