### ISSUE TITLE
Flemish meter no longer works with this setup

### ISSUE THREAD

**Issue by FreFre** [daniel-jong/esp8266_p1meter#38]
Dear

First of all, thank you for this solution. I have it running since november last year and it works like a charm. At least until a month or so, then the solution stopt working.

I've been trying to understand what is going on, but I'm a bit lost. What should be the content of one telegram? Should this be one line  or a complete set of lines? 

When check the content of a telegram, I do get mixed results. Sometimes it is just one line and sometimes are some lines or a lot of lines. See here below the set of data I get per telegram

Example 1
`0-0:96.1.4(50217)`

Example 2

```
0-0:96.1.1(3153414733313030313737323435)

0-0:1.0.0(230923191021S)

1-0:1.8.1(004556.575*kWh)

1-0:1.8.2(005324.382*kWh)

1-0:2.8.1(000564.096*kWh)

1-0:2.8.2(000195.911*kWh)

0-0:96.14.0(0002)

1-0:1.4.0(00.017*kW)
```

Example 3

```
1-0:62.7.0(00.254*kW)

1-0:32.7.0(239.1*V)

1-0:52.7.0(238.7*V)
1-0:72.7.0(239.1*V)

1-0:31.7.0(001.50*A)

1-0:51.7.0(001.44*A)

1-0:71.7.0(001.60*A)

0-0:96.3.10(1)

0-0:17.0.0(999.9*kW)

1-0:31.4.0(999*A)

0-0:96.13.0()

0-1:24.1.0(003)

0-1:96.1.1(37464C4F32313230303131323133)

0-1:24.4.0(1)

0-1:24.2.3(230923191005S)(02273.179*m3)

!78DE

/FLU5\253769484_A
```

I can't get my head around it.

Looking at the code I would expect one line since the read from serial is until \n

` int len = Serial.readBytesUntil('\n', telegram, P1_MAXLINELENGTH);`

But it seems like it doesn't recognizes the \n at the end of the lines.

Any help appreciated.

**Comment by fluppie** [comment]
Komt door de introductie van de kwartierpieken in het telegram ;-).
Known issue, see https://github.com/daniel-jong/esp8266_p1meter/issues/35#issuecomment-1706849584

**Comment by FreFre** [comment]
Closed.
See comment above.
